version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: Web/Dockerfile
    expose:
      - 80
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - api

  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    expose:
      - 80
    ports:
      - "8002:80"
      - "8003:443"
    depends_on:
      - web
